import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Register } from '@components/Register';

export default function Home() {
  return (
    <div className={styles.Form}>
      <Head>
        <title>Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Register />
    </div>
  );
}
